# Generated by Django 5.0.6 on 2024-05-24 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qf', '0002_areamedica_paciente_esperando_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dialogId', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UsusariosChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qf.chat')),
                ('id_paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qf.paciente')),
                ('id_quimico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='qf.quimicofarmaceutico')),
            ],
        ),
    ]
