# Generated by Django 5.0.6 on 2024-05-25 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qf', '0003_chat_ususarioschat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ususarioschat',
            name='id_chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qf.chat'),
        ),
        migrations.AlterField(
            model_name='ususarioschat',
            name='id_paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qf.paciente'),
        ),
        migrations.AlterField(
            model_name='ususarioschat',
            name='id_quimico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qf.quimicofarmaceutico'),
        ),
    ]
