# Generated by Django 5.0.6 on 2024-06-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qf', '0004_alter_ususarioschat_id_chat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='fotou',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='path/to/upload'),
        ),
    ]
