# Generated by Django 5.0.6 on 2024-06-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qf', '0006_alter_perfil_fotou_alter_perfil_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='fotou',
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='sexo',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
    ]
