# Generated by Django 5.0.6 on 2024-06-08 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qf', '0007_remove_perfil_fotou_perfil_foto_alter_perfil_sexo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id de la especialidad')),
                ('especialidad', models.CharField(max_length=20, verbose_name='nombre de la especialidad')),
            ],
        ),
        migrations.AlterField(
            model_name='areamedica',
            name='area_medica',
            field=models.CharField(max_length=20, verbose_name='nombre de la area'),
        ),
        migrations.AlterField(
            model_name='areamedica',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id de la area medica'),
        ),
        migrations.AddField(
            model_name='quimicofarmaceutico',
            name='especialidades',
            field=models.ManyToManyField(related_name='quimicos_farmaceuticos', to='qf.especialidad'),
        ),
    ]
