# Generated by Django 5.0.6 on 2024-06-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qf', '0009_quimicofarmaceutico_area_medica'),
    ]

    operations = [
        migrations.AddField(
            model_name='quimicofarmaceutico',
            name='calificacion',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quimicofarmaceutico',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
