# Generated by Django 5.0.6 on 2024-06-15 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qf', '0010_quimicofarmaceutico_calificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quimicofarmaceutico',
            name='calificacion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
