# Generated by Django 5.0.6 on 2024-06-18 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qf', '0011_alter_quimicofarmaceutico_calificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id del usuario')),
                ('nombre_usuario', models.CharField(max_length=20, verbose_name='nombre del usuario')),
                ('correo', models.CharField(max_length=25, verbose_name='ingresa un correo')),
                ('clave', models.CharField(max_length=16, verbose_name='ingresa una contraseña')),
                ('sexo', models.CharField(max_length=10)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('fecha_de_nacimiento', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios')),
            ],
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='user',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='id del paciente'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qf.usuario'),
        ),
        migrations.AddField(
            model_name='quimicofarmaceutico',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qf.usuario'),
        ),
    ]
