# Generated by Django 5.0.6 on 2024-06-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qf', '0012_usuario_remove_paciente_user_alter_paciente_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='patologias',
            field=models.ManyToManyField(related_name='paciente', to='qf.especialidad'),
        ),
    ]
