# Generated by Django 5.0.6 on 2024-06-21 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qf', '0013_paciente_patologias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enfermedad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id del paciente')),
                ('nombre', models.CharField(max_length=40)),
                ('medicamentos', models.TextField()),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qf.usuario')),
            ],
        ),
    ]
