# Generated by Django 5.0.6 on 2024-06-23 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qf', '0014_enfermedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='enfermedad',
            name='pato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='qf.especialidad'),
        ),
    ]
